# test_belgi.py
import pytest
from belgining_ascii_kodi import belgining_ascii_kodi

def test_belgi():
    assert belgining_ascii_kodi('A') == 65
    assert belgining_ascii_kodi('a') == 97
    assert belgining_ascii_kodi('1') == 49
    assert belgining_ascii_kodi('0') == 48
    assert belgining_ascii_kodi(' ') == 32
    assert belgining_ascii_kodi('\n') == 10
    assert belgining_ascii_kodi('\t') == 9
    assert belgining_ascii_kodi('\r') == 13
    assert belgining_ascii_kodi('\b') == 8
    assert belgining_ascii_kodi('\f') == 12
    assert belgining_ascii_kodi('\n') == 10
    assert belgining_ascii_kodi('\v') == 11
    assert belgining_ascii_kodi('\a') == 7
    assert belgining_ascii_kodi('\x00') == 0
    assert belgining_ascii_kodi('\x01') == 1
    assert belgining_ascii_kodi('\x02') == 2
    assert belgining_ascii_kodi('\x03') == 3
    assert belgining_ascii_kodi('\x04') == 4
    assert belgining_ascii_kodi('\x05') == 5
    assert belgining_ascii_kodi('\x06') == 6
    assert belgining_ascii_kodi('\x07') == 7
    assert belgining_ascii_kodi('\x08') == 8
    assert belgining_ascii_kodi('\x09') == 9
    assert belgining_ascii_kodi('\x0a') == 10
    assert belgining_ascii_kodi('\x0b') == 11
    assert belgining_ascii_kodi('\x0c') == 12
    assert belgining_ascii_kodi('\x0d') == 13
    assert belgining_ascii_kodi('\x0e') == 14
    assert belgining_ascii_kodi('\x0f') == 15
    assert belgining_ascii_kodi('\x10') == 16
    assert belgining_ascii_kodi('\x11') == 17
    assert belgining_ascii_kodi('\x12') == 18
    assert belgining_ascii_kodi('\x13') == 19
    assert belgining_ascii_kodi('\x14') == 20
    assert belgining_ascii_kodi('\x15') == 21
    assert belgining_ascii_kodi('\x16') == 22
    assert belgining_ascii_kodi('\x17') == 23
    assert belgining_ascii_kodi('\x18') == 24
    assert belgining_ascii_kodi('\x19') == 25
    assert belgining_ascii_kodi('\x1a') == 26
    assert belgining_ascii_kodi('\x1b') == 27
    assert belgining_ascii_kodi('\x1c') == 28
    assert belgining_ascii_kodi('\x1d') == 29
    assert belgining_ascii_kodi('\x1e') == 30
    assert belgining_ascii_kodi('\x1f') == 31
    assert belgining_ascii_kodi('\x20') == 32
    assert belgining_ascii_kodi('\x21') == 33
    assert belgining_ascii_kodi('\x22') == 34
    assert belgining_ascii_kodi('\x23') == 35
    assert belgining_ascii_kodi('\x24') == 36
    assert belgining_ascii_kodi('\x25') == 37
    assert belgining_ascii_kodi('\x26') == 38
    assert belgining_ascii_kodi('\x27') == 39
    assert belgining_ascii_kodi('\x28') == 40
    assert belgining_ascii_kodi('\x29') == 41
    assert belgining_ascii_kodi('\x2a') == 42
    assert belgining_ascii_kodi('\x2b') == 43
    assert belgining_ascii_kodi('\x2c') == 44
    assert belgining_ascii_kodi('\x2d') == 45
    assert belgining_ascii_kodi('\x2e') == 46
    assert belgining_ascii_kodi('\x2f') == 47
    assert belgining_ascii_kodi('\x30') == 48
    assert belgining_ascii_kodi('\x31') == 49
    assert belgining_ascii_kodi('\x32') == 50
    assert belgining_ascii_kodi('\x33') == 51
    assert belgining_ascii_kodi('\x34') == 52
    assert belgining_ascii_kodi('\x35') == 53
    assert belgining_ascii_kodi('\x36') == 54
    assert belgining_ascii_kodi('\x37') == 55
    assert belgining_ascii_kodi('\x38') == 56
    assert belgining_ascii_kodi('\x39') == 57
    assert belgining_ascii_kodi('\x3a') == 58
    assert belgining_ascii_kodi('\x3b') == 59
    assert belgining_ascii_kodi('\x3c') == 60
    assert belgining_ascii_kodi('\x3d') == 61
    assert belgining_ascii_kodi('\x3e') == 62
    assert belgining_ascii_kodi('\x3f') == 63
    assert belgining_ascii_kodi('\x40') == 64
    assert belgining_ascii_kodi('\x41') == 65
    assert belgining_ascii_kodi('\x42') == 66
    assert belgining_ascii_kodi('\x43') == 67
    assert belgining_ascii_kodi('\x44') == 68
    assert belgining_ascii_kodi('\x45') == 69
    assert belgining_ascii_kodi('\x46') == 70
    assert belgining_ascii_kodi('\x47') == 71
    assert belgining_ascii_kodi('\x48') == 72
    assert belgining_ascii_kodi('\x49') == 73
    assert belgining_ascii_kodi('\x4a') == 74
    assert belgining_ascii_kodi('\x4b') == 75
    assert belgining_ascii_kodi('\x4c') == 76
    assert belgining_ascii_kodi('\x4d') == 77
    assert belgining_ascii_kodi('\x4e') == 78
    assert belgining_ascii_kodi('\x4f') == 79
    assert belgining_ascii_kodi('\x50') == 80
    assert belgining_ascii_kodi('\x51') == 81
    assert belgining_ascii_kodi('\x52') == 82
    assert belgining_ascii_kodi('\x53') == 83
    assert belgining_ascii_kodi('\x54') == 84
    assert belgining_ascii_kodi('\x55') == 85
    assert belgining_ascii_kodi('\x56') == 86
    assert belgining_ascii_kodi('\x57') == 87
    assert belgining_ascii_kodi('\x58') == 88
    assert belgining_ascii_kodi('\x59') == 89
    assert belgining_ascii_kodi('\x5a') == 90
    assert belgining_ascii_kodi('\x5b') == 91
    assert belgining_ascii_kodi('\x5c') == 92
    assert belgining_ascii_kodi('\x5d') == 93
    assert belgining_ascii_kodi('\x5e') == 94
    assert belgining_ascii_kodi('\x5f') == 95
    assert belgining_ascii_kodi('\x60') == 96
    assert belgining_ascii_kodi('\x61') == 97
    assert belgining_ascii_kodi('\x62') == 98
    assert belgining_ascii_kodi('\x63') == 99
    assert belgining_ascii_kodi('\x64') == 100
    assert belgining_ascii_kodi('\x65') == 101
    assert belgining_ascii_kodi('\x66') == 102
    assert belgining_ascii_kodi('\x67') == 103
    assert belgining_ascii_kodi('\x68') == 104
    assert belgining_ascii_kodi('\x69') == 105
    assert belgining_ascii_kodi('\x6a') == 106
    assert belgining_ascii_kodi('\x6b') == 107
    assert belgining_ascii_kodi('\x6c') == 108
    assert belgining_ascii_kodi('\x6d') == 109
    assert belgining_ascii_kodi('\x6e') == 110
    assert belgining_ascii_kodi('\x6f') == 111
    assert belgining_ascii_kodi('\x70') == 112
    assert belgining_ascii_kodi('\x71') == 113
    assert belgining_ascii_kodi('\x72') == 114
    assert belgining_ascii_kodi('\x73') == 115
    assert belgining_ascii_kodi('\x74') == 116
    assert belgining_ascii_kodi('\x75') == 117
    assert belgining_ascii_kodi('\x76') == 118
    assert belgining_ascii_kodi('\x77
